import { Category, Product, Shop } from '../types';

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat_all', name: 'Barchasi', iconName: 'grid' },
  { id: 'cat_wafers', name: 'Vaflilar', iconName: 'layers' },
  { id: 'cat_chocolate', name: 'Shokoladlar', iconName: 'award' },
  { id: 'cat_cookies', name: 'Pechenyelar', iconName: 'disc' },
  { id: 'cat_candies', name: 'Karamellar', iconName: 'circle' },
  { id: 'cat_marmalade', name: 'Marmeladlar', iconName: 'heart' },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    code: 'QND-001',
    name: 'Shokoladli Vafli "Krem-Bryule" 200g',
    categoryId: 'cat_wafers',
    categoryName: 'Vaflilar',
    description: 'Yumshoq krem-bryule qatlami bilan qoplangan qarsildoq vafli',
    priceDona: 12000,
    priceBlok: 110000,   // 10 dona
    priceKorobka: 420000,// 40 dona
    priceKg: 55000,
    itemsPerBlock: 10,
    itemsPerBox: 40,
    stockDona: 850,
  },
  {
    id: 'prod_2',
    code: 'QND-002',
    name: 'Limonli Shirin Vafli 180g',
    categoryId: 'cat_wafers',
    categoryName: 'Vaflilar',
    description: 'Tabiiy limon ekstrakti va vanil qoʻshilgan yengil vafli',
    priceDona: 10000,
    priceBlok: 92000,
    priceKorobka: 350000,
    priceKg: 50000,
    itemsPerBlock: 10,
    itemsPerBox: 40,
    stockDona: 620,
  },
  {
    id: 'prod_3',
    code: 'QND-003',
    name: 'Qora Shokolad "Alp Togʻlari" 90g (72%)',
    categoryId: 'cat_chocolate',
    categoryName: 'Shokoladlar',
    description: 'Haqiqiy kakao moyidan tayyorlangan achchiq shokolad plitkasi',
    priceDona: 16000,
    priceBlok: 180000,   // 12 dona
    priceKorobka: 680000,
    priceKg: 95000,
    itemsPerBlock: 12,
    itemsPerBox: 48,
    stockDona: 1200,
  },
  {
    id: 'prod_4',
    code: 'QND-004',
    name: 'Sutli Shokolad "Yongʻoqli Zavq" 100g',
    categoryId: 'cat_chocolate',
    categoryName: 'Shokoladlar',
    description: 'Butun funduk yongʻoqlari bilan boyitilgan nozik sutli shokolad',
    priceDona: 18000,
    priceBlok: 200000,
    priceKorobka: 760000,
    priceKg: 105000,
    itemsPerBlock: 12,
    itemsPerBox: 48,
    stockDona: 940,
  },
  {
    id: 'prod_5',
    code: 'QND-005',
    name: 'Suli Pechenyesi "Klassik" 350g',
    categoryId: 'cat_cookies',
    categoryName: 'Pechenyelar',
    description: 'Mayizli va dolchinli foydali anʼanaviy suli pechenyesi',
    priceDona: 14000,
    priceBlok: 110000,
    priceKorobka: 410000,
    priceKg: 40000,
    itemsPerBlock: 8,
    itemsPerBox: 32,
    stockDona: 430,
  },
  {
    id: 'prod_6',
    code: 'QND-006',
    name: 'Shokolad Tomchili "Cookies" 220g',
    categoryId: 'cat_cookies',
    categoryName: 'Pechenyelar',
    description: 'Amerika uslubidagi xushboʻy pechenye, qora shokolad tomchilari bilan',
    priceDona: 15000,
    priceBlok: 140000,
    priceKorobka: 520000,
    priceKg: 65000,
    itemsPerBlock: 10,
    itemsPerBox: 40,
    stockDona: 510,
  },
  {
    id: 'prod_7',
    code: 'QND-007',
    name: 'Meva Taʼmli Karamellar 1kg (Assorti)',
    categoryId: 'cat_candies',
    categoryName: 'Karamellar',
    description: 'Olma, qulupnay, apelsin va malina taʼmli jiloli karamellar',
    priceDona: 28000,
    priceBlok: 135000,   // 5 x 1kg
    priceKorobka: 260000,// 10 x 1kg
    priceKg: 28000,
    itemsPerBlock: 5,
    itemsPerBox: 10,
    stockDona: 340,
  },
  {
    id: 'prod_8',
    code: 'QND-008',
    name: 'Meva Sharbatli Marmelad Ayiqchalar 150g',
    categoryId: 'cat_marmalade',
    categoryName: 'Marmeladlar',
    description: 'Tabiiy meva sharbatlari bilan tayyorlangan mayin saqichli marmelad',
    priceDona: 9000,
    priceBlok: 85000,
    priceKorobka: 320000,
    priceKg: 60000,
    itemsPerBlock: 10,
    itemsPerBox: 40,
    stockDona: 780,
  },
];

export const SEED_SHOPS: Shop[] = [
  {
    id: 'shop_1',
    name: 'Oqtepa Minimarket',
    ownerName: 'Akmal aka',
    phone: '+998 90 123 45 67',
    address: 'Toshkent sh., Chilonzor 9-mavze, 14-uy',
    latitude: 41.2858,
    longitude: 69.2045,
    debtBalance: 1250000,
    visitDay: 'Dushanba',
    createdAt: new Date().toISOString(),
    isSynced: true,
  },
  {
    id: 'shop_2',
    name: 'Baraka Baqqollik Doʻkoni',
    ownerName: 'Dilshod Raximov',
    phone: '+998 97 765 43 21',
    address: 'Toshkent sh., Bunyodkor koʻchasi, 45-uy',
    latitude: 41.2789,
    longitude: 69.2198,
    debtBalance: 0,
    visitDay: 'Dushanba',
    createdAt: new Date().toISOString(),
    isSynced: true,
  },
  {
    id: 'shop_3',
    name: 'Shirinliklar Olami',
    ownerName: 'Feruza opa',
    phone: '+998 93 555 12 34',
    address: 'Toshkent sh., Yunusobod 11-mavze, 2-uy',
    latitude: 41.3654,
    longitude: 69.2876,
    debtBalance: 4800000,
    visitDay: 'Seshanba',
    createdAt: new Date().toISOString(),
    isSynced: true,
  },
  {
    id: 'shop_4',
    name: 'Ziyo Oziq-Ovqat',
    ownerName: 'Jamshid Karimov',
    phone: '+998 99 888 77 66',
    address: 'Toshkent sh., Mirzo Ulugʻbek tumani, Qorasuv-1',
    latitude: 41.3289,
    longitude: 69.3412,
    debtBalance: 320000,
    visitDay: 'Chorshanba',
    createdAt: new Date().toISOString(),
    isSynced: true,
  },
  {
    id: 'shop_5',
    name: 'Farovon Supermarket',
    ownerName: 'Nodirbek',
    phone: '+998 91 234 56 78',
    address: 'Toshkent sh., Sergeli 7-mavze, Yangi Sergeli koʻchasi',
    latitude: 41.2214,
    longitude: 69.2234,
    debtBalance: 0,
    visitDay: 'Payshanba',
    createdAt: new Date().toISOString(),
    isSynced: true,
  },
];
